[package]
name = "epic-mickey-launcher"
version = "0.4.3"
description = "launcher"
authors = ["Jonas Kalsvik"]
license = "MIT"
repository = "Epic-Mickey-Launcher"
edition = "2021"
rust-version = "1.57"

[build-dependencies]
tauri-build = { version = "1.5.1", features = [] }

[dependencies]
tokio-stream = "0.1.14"
sevenz-rust = "0.2.11"
dirs-next = "2.0.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.6.2", features = [ "api-all"] }
zip-extract = "0.1.2"
reqwest = {version = "0.11.13", features = ["stream"] }
walkdir = "2.3.2"
bytes = "1.4.0"
json = "0.12.4"
futures-util = "0.3.14"
open = "4.1.0"
registry = "1.2.3"
shutil = "0.1.2"
tauri-plugin-deep-link = "0.1.1"
fix-path-env = { git = "https://github.com/tauri-apps/fix-path-env-rs" }
chrono = "0.4.31"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
